### ISSUE TITLE
Legacy wallpapers

### ISSUE THREAD

**Issue by iloveclang** [BunsenLabs/bunsen-images#15]
Would it be at all possible to make some kind of bunsen-images-old, which contained all the old wallpapers, some of which were absolute bangers. New ones are ok, but I would personally prefer some of the older options since they offer the  dark-blueish vibe that is missing currently.

Would be cool if installing this was an option in the first setup dialogue

**Comment by hhhorb** [comment]
Sorry for the late reply, is this what your looking for?

https://github.com/BunsenLabs/bunsen-images-extra

**Comment by iloveclang** [comment]
yes, thank you!
