### ISSUE TITLE
png or jpg

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-images#2]
Debian specification asks for png for wallpapers, but most of the ones we have been liking have gradients plus noise texture, which sends the file size way up (in the region of 2-3MB for the bigger sizes) 

The latest lot that I have uploaded here are jpg. Because they are wallpaper collections, with a variety of sizes, then resizing shouldn't be needed, so jpgs are fine IMO.

Your thoughts?

**Comment by Sector11** [comment]
I agree.  With my eyes I'd never see the difference but my HDD would.

**Comment by hhhorb** [comment]
I have no problem with JPGs. Most people will end up installing their own anyway, don't you think?

**Comment by ben2s** [comment]
Personally I don't like jpg because of the artifacts - although admittedly with a well-chosen compression level they can be minimal.
Bottom line: I prefer png, but I'm fine either way.

**Comment by Sector11** [comment]
If I touch any of my wife's 248 wallpapers, jpg and png, I'm dead.  So yes, hhhorb is correct.  I clean mine out every now an then, except for a few {rolls eyes} untouchables, then start collecting all over ... 

How many are going to be included in the Live Install?

**Comment by hhhorb** [comment]
I just downloaded the master zip and am looking at the wallpapers folder.

I take it back. I'm viewing these at 1280x800 and some of them look particularly blurry and grainy to me, namely the ones that are close to my monitor's resolution. The green (turquiose, to my eyes) ones look the best on my screen, that could just be my monitor favoring that color.

I'd prefer we have fewer images with better resolution. In addition, I'd prefer if we had less variety of colors and sizes and more variety of styles. We could get away with one large, hi-quality widescreen and one fullscreen image in each color and style and keep the package size down that way, that's what Philip did for #! IIRC. What do you think?

damo, since many of these images are yours, I hope you don't take this criticism personally. I'm completely blown away by how much work you've put into BL.

**Comment by capn-damo** [comment]
No probs :)

I'd just like to get things moving really, and putting some choices out there. Whatever gets included as default is fine by me....as long as it looks good, and satisfies as many as possible. I will put the collections up on dA anyway, so I'm just anticipating that and getting some of the work done now.

The problem with gradients is banding - either due to the low bit depth of the graphics app, or the monitor capability - which is why it is handy to put some noisy texture on it to disguise it. But that puts the file size way up for an RGB image. I used 16bit Gimp 2.9 at 300dpi, but still see banding (no idea if it is the monitor though :( )

Which images look blurry to you Has?

I think a hint of colour would be good, to make some distinction with crunchbang monochrome. It could go with the grub screen, and the gtk/OB themes (re. Bunsen2-blue)

**Comment by hhhorb** [comment]
Yeah, you had asked on the forums about banding in my Lines desaturation... that's actually present in the original files, desaturating it or changing it to another color than blue/turquoise just makes it more visible. If you create a gradient using GIMP's gradient tool, having it's Dithering box checked is supposed to help.

re: Which images look blurry to you Has? The ones at 1280x1024 look the worst on my monitor, but this may be deceiving as the larger images are getting resized in my image viewer (gpicview). The logos and text still seem blurrier to me than the other resolutions if I view them at actual size, though.

The Hydrogen emission spectrum really looks blurry. Ututo's logos and text seems weird, maybe I just don't like that outlined effect.

The images in the master folder are PNGs and none is much larger than 2MB. I have JPGs from the Internet that are that size but seem to have better quality, so we should be able to fix this.

I suggest we come to a consensus about what styles we'll include and then we can work on the quality, sizes and colors. Should we ask about people's preferences in one of the open threads, just poll the BL team or just decide between the 2 of us based on what we've seen of opinions on the forum?

Here's are my suggestions for what we include, which is outside of the scope of this GitHub issue, so it will need it's own forum thread eventually but I'll post it here to start to get feedback. Substitute "I suggest should be" where I write "will be"...

~The default GTK/Openbox/notification/lightdm theme will be #! in color but with a selected background color in turquoise as an homage to jessie, with an all grey theme also included.

~2 additional themes with light text on dark backgrounds will also be included, again with matching Openbox/notification and lightdm themes.

~The original Waldorf themes will be included with a working GTK3 theme added that will match close enough to be usable.

~Other theme colors and sizes can be included in a "themes-extra" package.

~The walls will each come in 2 color schemes, one in turquoise and one in greyscale to match the themes, and 2 sizes, a large fullscreen format and a large widescreen format. 

~Wallpaper styles will be "velvet noise", the BL logo on a gradient or glow both with and without text, damo's lines logo on a gradient or glow with and without text, and the Hydrogen spectrum if possible.

~Other walls can be included in a "wallpapers-extra" package.

How does that sound?

**Comment by hhhorb** [comment]
And since I've polluted this issue with the above comments, I'd almost suggest that your bl-flame-graph-green-1920x1080.jpg image be the default wall but in PNG format.

Half of me wants to see it as the default, and half wants the default to be the regular BL logo and have this image included in the default wall pack. I'm leaning towards the latter.

**Comment by capn-damo** [comment]
I pretty much agree with all you have suggested above. (I'll revisit those images with your eyes if I can!)

My blue lines wall is my personal fave (!), along with ututo's velvet-noise with logo. The problem with having text is distortion if the screen proportion is different from the default wallpaper - it isn't so noticeable with the logo. Unless nitrogen is set with eg "centered" of course, maybe with a close screen bg color.

I'm not happy with the spectrum walls anyway - it could be a lot better. I'll do some work there over the next day or two, and see how png v. jpg works out.

And the easiest way out is for us to decide among ourselves! Maybe come up with a first choice proposal, and get responses on the forum. If there is a lot of negative feedback we can re-think, but at least people should feel included to some extent.

Another thought is to have an icon set to match the tinted themes!

**Comment by Sector11** [comment]
I guess I'm not much of an Art Critic - I like them all.  Although blue is my favourite the one wallpaper my size is lighter then the rest in the collection; bl-lines-blue-1920x1080.jpg  Still I do like it and have to admit - because I went looking - I now see the gradient lines that I missed before.  Blue is my colour.  Although I like the greys as well.  This in particular is nice: bl_bgpack_ututo/bl_1920x1080a.png

Another two observations - opinions
1 the two bl-grub-nebula ones are AWESOME - but might be a but busy maybe?
2. leave the green to debian

**Comment by capn-damo** [comment]
You are right - that one is a bit lighter. I thought I had checked them all :(

The grub nebula ones looked a lot better in the original idea I did a while ago. Maybe I should take out the "star" noise.

It's great to have other eyes on images though, to pick up on things I've missed late at night!

**Comment by hhhorb** [comment]
Text distortion doesn't happen if nitrogen sets the image with "Zoomed fill". I think I'll do a mockup this evening and I'll shoot damo a PM via the forums when it's done so he can do the icon tinting, then we can forward that to the other team members for criticism, then reveal it in a forum post when we see fit.

**Comment by Sector11** [comment]
@ damo - you change the grub nebula ones all you want - but know this - I have them here. I like them and will try them.  If not to "busy" for the grub list I just might hang on to them.  They would also make great capt-damo wallpapers in some DeviantArt site someplace ... [rolls eyes]  hehehehe

@ hhhorb - I've never tried "zoomed fill" all mine are sized or cropped by me if I can't find the right size.  Must give that a test.

**Comment by capn-damo** [comment]
If using zoomed fill then edges are clipped, so it isn't suitable if there are details near the edges, or their positions are important. It's easy enough to accommodate that though if the default nitrogen setting will be zoomed-fill instead of automatic, and we can then leave out some of the bg sizes as hhh suggests. So png's are back on the agenda :D

**Comment by johnraff** [comment]
*-extras packages seems like the way to go, especially for wallpapers. Do themes occupy so much space that there would be a need to separate some out into an optional package?

Thanks for the head-up on the default nitrogen setting. I can't find any documentation, but would it be correct to assume that "mode=5" in bg-saved.cfg would set "zoomed fill"?

**Comment by capn-damo** [comment]
Couldn't find any documentation either, but experimenting gives:

mode=0      scaled
mode=1      tiled
mode=2      centered
mode=3      zoomed
mode=4      automatic
mode=5      zoomed-fill

**Comment by hhhorb** [comment]
re: theme space, I guess they could all go in one package. Themes are small.
