### ISSUE TITLE
No license provided for bunsen-images

### ISSUE THREAD

**Issue by cpoakes** [BunsenLabs/bunsen-images#3]
There is/are no license(s) provided for bunsen-images content.

**Comment by ghost** [comment]
Licenses/attribution will be provided as debian-formatted copyright files; these files will be created as we finalise the Debian packages. (Partial) coverage of the wallpaper works is available at https://github.com/2ion/bunsen-artwork-prerelease/blob/bunsen-wallpapers/debian/copyright as part of a prereleased wallpaper collection package.

Don't worry, we keep track of that stuff and aim at Debian policy compliance with our packages. This includes giving contributors all the respect and attribution they deserve.

 We are currently discussing about how to package all the artwork internally, so you can expect progress on this topic soon.

I'll keep this open until things are done

**Comment by cpoakes** [comment]
Thanks for the cross reference.  I figured licensing would eventually be added with packaging. It is just nice to have the license available now as I can download them now.

**Comment by johnraff** [comment]
Closed, since LICENSE and debian/copyright are now installed.
