### ISSUE TITLE
Repository is very big - split?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-images#4]
This makes for a big download and time-consuming install.
I would suggest putting the bl-default/ images in a **bunsen-images-default** package and the others in **bunsen-images-full**. The "default" package can be a hard dependency of "full", so users just have to install one or the other.

Does that make sense?

**Comment by ghost** [comment]
Wouldn't it be sensible to include all bl-* folders plus icon-avatar/ and svg/ into the default package and just package the wallpapers/ directory separately, the reason being that bl-grub and bl-login are, as their names imply, going to be used in the system anyway (for grub and login purposes, or aren't they by default?). icon-avatar/ and svg/ are basically free anyway.

**Comment by johnraff** [comment]
bl-default contains one image each for grub and login, and four wallpapers (total 5.5MB). That should be enough for a basic setup. bl-grub,login have many more alternative images.

I was thinking about a possible future attempt to build a BunsenLite when bunsen-images-default might be useful. Agreed, icon-avatar and svg could go in too, without adding any extra weight, but bl-login is 9MB by itself, and bl-grub adds another 1MB.

So perhaps bl-login, bl-grub and wallpapers to go in bunsen-images-full?

**Comment by capn-damo** [comment]
Wasn't there a previous suggestion to have the basic setup artwork, and the rest in a "bunsen-extras" package?

**Comment by johnraff** [comment]
That's what I'm suggesting here really, but with the big package called bunsen-images-full, or bunsen-images-all or... bunsen-images-extra would be OK too I guess. Or would bunsen-extras have something other than images?

**Comment by capn-damo** [comment]
`bunsen-images-extra` sounds a good descriptive name, but `bunsen-extras` could include the extra images, as well as future scripts and any other goodies we come up with.

**Comment by johnraff** [comment]
Maybe better to keep the images by themselves? By comparison, scripts are very small and someone who wanted to install some extra gadgets might not want to be obliged also to install 50MB of image files. Maybe a future bunsen-extras (bunsen-doodahs came up for a sound file) for small stuff like scripts?

About naming, I can see two possible patterns:
1) **bunsen-images-default** which is a hard dependency of **bunsen-images-all**, so installing just -images-all will automatically bring -images-default as well.

2) **bunsen-images-default** and **bunsen-images-extra**. To get the full set a user has to install both packages. OTOH, with this scheme installing -images-extra without images-default is a possibility.

(In both schemes, -images-default will also be a dependency of bunsen-configs.)

I was initially thinking of 1) but maybe there would be users who might prefer 2)?

**Comment by ghost** [comment]
Revisiting this (while waiting for the repo to clone on my slooow connection :D)

I do not think it makes any sense to split the actual repository as it is. The cloning of this repo would still take as long because the history is being preserved, _adding_ the clone time of the split-out repo. The solution to this: erase the history of this repo (re-commit everything as-it-is minus what we want to split out). Either this or...

Otherwise, I would favour just building two packages, _bunsen-images_ and _bunsen-images-extra_ (using a common pattern in Debian, it's not necessary to name a package 'default').

Thoughts?

**Comment by Sector11** [comment]
I like the idea of two packages `bunsen-images` and `bunsen-images-extra`.  _no scripts in either_ just images.  Keep what comes with the ISO light - half a dozen max ... put the rest in the extra package

**Comment by capn-damo** [comment]
Sounds reasonable.
`bunsen-images-extra` as a bl-welcome option?

**Comment by Sector11** [comment]
That sounds good ... also does BunsenLabs have a DeviantArt page?

**Comment by capn-damo** [comment]
I set up a DA BunsenLabs group months ago, just in case anyone else had the idea and grabbed the name ;)
The idea is for it to be a repository for scrots, wallpapers, OB/GTK themes, conkys, tint2s, etc.

I've been waiting for a BL release before publicizing it or uploading anything, but it could be done anytime I guess.

**Comment by Sector11** [comment]
Good Thinking...  if you're looking for opinions ... I'd wait until Hydrogen is released to the masses. :+1:

**Comment by johnraff** [comment]
To quote @2ion 

> I would favour just building two packages, bunsen-images and bunsen-images-extra (using a common pattern in Debian, it's not necessary to name a package 'default').

This sounds good. Let's build the two .deb packages out of the same **bunsen-images** repository. When we get to the point of distributing .deb files instead of source repos then users will have the option of installing only the default set and saving bandwidth/disk space.

**Comment by ghost** [comment]
@johnraff I did the split. Since the name of bunsen-images doesn't change (including debhelper invocations) I guess we don't have to fix the netinstall script to reflect this right?

**Comment by johnraff** [comment]
It's fine. The script as-is builds both .debs (this is unavoidable and anyway the whole repo is downloaded) then installs bunsen-images only. bunsen-images-extra is left on the user's local repository to install if desired. Anyway, it illustrates the principle, and when we go to debs on a repo the two will be downloadable separately.
