### ISSUE TITLE
Bunsenlabs-flame-256.svg installation location

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-images#7]
`svg/Bunsenlabs-flame-256.svg` needs to be installed in `/usr/share/pixmaps`

**Comment by johnraff** [comment]
It will be renamed distributor-logo-bunsenlabs.svg and installed in /usr/share/icons/hicolor/scalable/places.
A symlink in /usr/share/pixmaps named bunsenlabs-flame.svg will point to that file.

**Comment by capn-damo** [comment]
Thanks :)
